### ISSUE TITLE
Wrong validation of allowed domains

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-panel#17]
When attempting to add a new domain to the list of allowed domains of an app (http://hosting.com/my-apps/test-app/edit) the validation is not validating some valid URL's like the following:
- http://www.google.com
- http://localhost.com:8080

Also there's a blank error message.

![screen shot 2016-10-11 at 4 16 38 pm](https://cloud.githubusercontent.com/assets/4240006/19289035/682627c2-8fce-11e6-9aac-9eb4090f0097.png)

**Comment by roddolf** [comment]
`http://localhost:8080.com` should not be a valid address.
The port should be after the `.com`, e.g.:
 - `http://the-domain.com:8080`, or
 - `http://localhost:8080`

**Comment by alvaro9210** [comment]
This bug has already been fixed and it's been merged into develop. Now it's pending release.
I'll proceed to close the issue.
