### ISSUE TITLE
Add feature to create Access Points in DocumentExplorer

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-panel#29]
Add an option to create an Access Point to a document.
This feature must allow the user to set the following:
- slug (optional)
- memberShipResource
- hasMemberRelation
- isMemberOfRelation (optional)

**Comment by MiguelAraCo** [comment]
Please create another branch and apply the following changes:
- `hasMemberRelation` and `isMemberOfRelation` should be lower case
- `hasMemberRelation` shouldn't have a default when creating access points
- `hasMemberRelation` shouldn't have as an example ldp:member. Place as an example in the `slug` input `daughters/`, in `hasMemberRelation` `http://example.com/ns#daughter` and in `isMemberOfRelation` `http://example.com/ns#father`
- The validation shouldn't be triggered until the input loses focus. Right now each keypress makes the error messages appear.
- `hasMemberRelation` and `isMemberOfRelation` can have any URI as a value, they are not limited to be a fragment URI
