### ISSUE TITLE
Add screen to manage Agents of an App

### ISSUE THREAD

**Issue by alvaro9210** [CarbonLDP/carbonldp-panel#38]
We need a new screen in which we can list and manage the Agents of an Application in which we could do the following:
 - List agents
 - Create agents
 - Edit agent data ( name, email, password, isItEnabled and its roles )
 - Delete agents

**Comment by codyburleson** [comment]
This sounds like something we might want to spend a little design time on together next week if time permits.

**Comment by MiguelAraCo** [comment]
@codyburleson you are right. We had a preliminary discussion around the requisites for the UI. Alvaro is working on an initial design to iterate over it. We should meet next week to finalize it and start its development.

**Comment by MiguelAraCo** [comment]
@alvaro9210 please split this task into two separate tasks (one for the Agents UI and one for the App Roles UI)

**Comment by alvaro9210** [comment]
This feature was merged with #40 - Add screen to manage agents of an app
Closing issue.
